name: pytest
on: pull_request

jobs:
  pytest:
    strategy:
      fail-fast: true
      matrix:
        python-version: ['3.10']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup ImageMagick
        run: sudo apt-get install -y imagemagick
      - uses: actions/setup-python@v4
        name: setup Python
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'
      - name: Install dependencies
        run: poetry install --all-extras
      - name: mypy
        run: poetry run mypy .
      - name: Pytest
        run: poetry run pytest --junitxml=pytest.xml --cov=magick_tile --cov-report=term-missing:skip-covered | tee pytest-coverage.txt
      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./pytest-coverage.txt
          junitxml-path: ./pytest.xml
